/**
 * content/blog → D1 full import (post-v1.5 CMS: one-time "MD → database" migration / later backup restore)
 *
 * Usage:
 *   pnpm content:import            generate SQL only (scripts/generated/import-md.sql)
 *   pnpm content:import:local      generate and apply to local D1
 *   pnpm content:import:prod       generate and apply to remote D1
 *
 * Properties:
 * - Idempotent: safe to re-run
 * - Imports full body; frontmatter syncs metadata
 * - Multilingual: `<slug>.<locale>.md` sidecar files (e.g. my-post.en.md) import per-locale translations;
 *   locales without sidecars are maintained in the Admin editor
 * - Preserves runtime data: views / pinned are never overwritten
 * - Deleted posts are removed from D1 (tags/translations cleaned up accordingly)
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = path.join(root, 'content', 'blog');
const outDir = path.join(root, 'scripts', 'generated');
const outFile = path.join(outDir, 'import-md.sql');

const target = process.argv[2]; // --local | --remote | undefined

const BASE_LOCALE = 'zh-tw';
/** Translation locales usable as sidecar suffixes (base language uses the main file) */
const TRANSLATION_LOCALES = ['zh-cn', 'en', 'jp'] as const;

function sqlString(value: string | undefined | null): string {
	if (value === undefined || value === null) return 'NULL';
	return `'${value.replaceAll("'", "''")}'`;
}

interface Translation {
	locale: string;
	title: string;
	summary: string;
	body: string;
}

interface PostRow {
	slug: string;
	cover?: string;
	date: string;
	published: boolean;
	tags: string[];
	/** Per-locale content (zh-tw comes from the <slug>.md main file) */
	translations: Translation[];
}

const files = readdirSync(contentDir).filter((f) => f.endsWith('.md'));

/** Main file (base language) + sidecar translations → PostRow list */
const rows: PostRow[] = [];

/** Body guard (Phase 44): md files may carry CRLF; normalize to LF before insert */
const lf = (v: string): string => v.replace(/\r\n?/g, '\n');
/** YYYY-MM-DD → epoch ms INTEGER (published_at is timestamp_ms; strings would poison sort typing) */
const dateMs = (d: string): string => (d ? String(Date.parse(`${d}T00:00:00Z`)) : 'NULL');

for (const file of files) {
	const slug = file.replace(/\.md$/, '');
	// sidecars (my-post.en.md) are handled inside the main-file loop; skip here
	if (TRANSLATION_LOCALES.some((l) => slug.endsWith(`.${l}`))) continue;

	const raw = readFileSync(path.join(contentDir, file), 'utf-8');
	const { data, content } = matter(raw);

	const rawDate = data.date;
	const date =
		rawDate instanceof Date
			? rawDate.toISOString().slice(0, 10)
			: String(rawDate ?? '').slice(0, 10);

	const translations: Translation[] = [
		{
			locale: BASE_LOCALE,
			title: String(data.title ?? slug),
			summary: String(data.summary ?? ''),
			body: lf(content)
		}
	];

	for (const locale of TRANSLATION_LOCALES) {
		const sidecar = `${slug}.${locale}.md`;
		if (!files.includes(sidecar)) continue;
		const side = matter(readFileSync(path.join(contentDir, sidecar), 'utf-8'));
		translations.push({
			locale,
			title: String(side.data.title ?? `${slug} (${locale})`),
			summary: String(side.data.summary ?? ''),
			body: lf(side.content)
		});
	}

	rows.push({
		slug,
		cover: typeof data.cover === 'string' ? data.cover : undefined,
		date,
		published: data.draft !== true,
		tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
		translations
	});
}

const now = new Date();
const nowMs = now.getTime();
const lines: string[] = ['-- generated by scripts/import-md.ts — do not edit'];

for (const row of rows) {
	lines.push(
		`INSERT INTO posts (id, slug, cover, published, published_at, created_at, updated_at)
VALUES (${sqlString(`post:${row.slug}`)}, ${sqlString(row.slug)}, ${sqlString(row.cover)}, ${row.published ? 1 : 0}, ${dateMs(row.date)}, ${nowMs}, ${nowMs})
ON CONFLICT(slug) DO UPDATE SET
	cover = excluded.cover,
	published = excluded.published,
	published_at = excluded.published_at,
	updated_at = excluded.updated_at;`
	);

	for (const tr of row.translations) {
		lines.push(
			`INSERT INTO post_translations (id, post_id, locale, title, summary, body, created_at, updated_at)
VALUES (${sqlString(`tr:${row.slug}:${tr.locale}`)}, ${sqlString(`post:${row.slug}`)}, ${sqlString(tr.locale)}, ${sqlString(tr.title)}, ${sqlString(tr.summary)}, ${sqlString(tr.body)}, ${nowMs}, ${nowMs})
ON CONFLICT(post_id, locale) DO UPDATE SET
	title = excluded.title,
	summary = excluded.summary,
	body = excluded.body,
	updated_at = excluded.updated_at;`
		);
	}
}

const allTags = [...new Set(rows.flatMap((r) => r.tags))];
for (const tag of allTags) {
	lines.push(
		`INSERT INTO tags (id, name, slug) VALUES (${sqlString(`tag:${tag}`)}, ${sqlString(tag)}, ${sqlString(tag.toLowerCase())})
ON CONFLICT(name) DO NOTHING;`
	);
}

for (const row of rows) {
	for (const tag of row.tags) {
		lines.push(
			`INSERT OR IGNORE INTO post_tags (post_id, tag_id) VALUES (${sqlString(`post:${row.slug}`)}, ${sqlString(`tag:${tag}`)});`
		);
	}
}

// Remove posts that no longer exist / tags no longer used
const slugList = rows.map((r) => sqlString(r.slug)).join(', ') || "''";
lines.push(
	`DELETE FROM post_tags WHERE post_id IN (SELECT id FROM posts WHERE slug NOT IN (${slugList}));`,
	`DELETE FROM posts WHERE slug NOT IN (${slugList});`,
	`DELETE FROM tags WHERE id NOT IN (SELECT tag_id FROM post_tags);`
);

const sql = lines.join('\n\n') + '\n';
mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, sql);
console.log(
	`✓ SQL written to ${path.relative(root, outFile)} (${rows.length} posts, ${allTags.length} tags, body included)`
);

if (target === '--local' || target === '--remote') {
	const flag = target;
	execFileSync('pnpm', ['wrangler', 'd1', 'execute', 'kikigaki', flag, `--file=${outFile}`], {
		cwd: root,
		stdio: 'inherit'
	});
	console.log(`✓ Imported to D1 (${flag.replace('--', '')})`);
} else {
	console.log('  套用到本地：pnpm content:import:local');
	console.log('  套用到遠端：pnpm content:import:prod');
}
